### ISSUE TITLE
[Feature]: Make it possible to view details of a shortened URL

### ISSUE THREAD

**Issue by XLTechie** [nvdaes/urlShortener#14]
### Problem

Currently, when viewing the list of already shortened URLs, it is only possible to view the name/description of the URL. Sometimes, if one has forgotten the custom URL for example, it would be nice to view the entire record.

### Suggestion

It is suggested to add a "view details" button, which opens a Window showing read-only field versions of the fields used when creating a URL.
That is:
* The name,
* the actual URL that has been shortened, and
* the custom URL or shortened version of the URL.

**Comment by nvdaes** [comment]
A gui.message>Box with ok and information icon can be used. I"ll create a pr probably tomorrow. Enviado desde mi iPhoneEl 24 jun 2023, a las 9:03, Luke Davis ***@***.***> escribió:﻿
Problem
Currently, when viewing the list of already shortened URLs, it is only possible to view the name/description of the URL. Sometimes, if one has forgotten the custom URL for example, it would be nice to view the entire record.
Suggestion
It is suggested to add a "view details" button, which opens a Window showing read-only field versions of the fields used when creating a URL.
That is:

The name,
the actual URL that has been shortened, and
the custom URL or shortened version of the URL.

Alternatives
No response
Additional context
No response

**Comment by XLTechie** [comment]
Thank you for your consideration.

Keep in mind that gui.messageBox (really gui.message.messageBox) is only 
supposed to be used for modal messages that will prevent things like NVDA exit 
if they are not resolved. That seems overkill for this.

**Comment by nvdaes** [comment]
In fact I prefer to use a multiline edit box, but for some reason I
thought that you would prefer a gui.messageBox control.
Let's use a readonly edit control like I did in placeMarkers. I'll
look also the control used on the store.

2023-06-25 7:20 GMT+02:00, Luke Davis ***@***.***>:

**Comment by XLTechie** [comment]
I hope soon to have a modeless message box available in NVDA, if NV Access 
approves some work I have in an upcoming PR.

But my own business schedule has interrupted getting that done before the end of 
next month.

**Comment by XLTechie** [comment]
> In fact I prefer to use a multiline edit box, but for some reason I thought that you would prefer a gui.messageBox control.

I think you remember me telling Sean I didn't like the multi line controls for 
the description in the add-on store. In fact the issue there is that they were 
not read all at once, which I thought users would expect in that situation. But 
I don't think users would have that expectation here.

Really any control you think would fit best would be fine in my opinion, just 
not gui.messageBox because too much NVDA internal nonsense is wrapped around it.

**Comment by nvdaes** [comment]
Yes, in fact I remember your opinion about the descriptions in the store. I created a pr for this issue, to be merged soon.Enviado desde mi iPhoneEl 26 jun 2023, a las 10:40, Luke Davis ***@***.***> escribió:﻿
> In fact I prefer to use a multiline edit box, but for some reason I thought that you would prefer a gui.messageBox control.

I think you remember me telling Sean I didn't like the multi line controls for 
the description in the add-on store. In fact the issue there is that they were 
not read all at once, which I thought users would expect in that situation. But 
I don't think users would have that expectation here.

Really any control you think would fit best would be fine in my opinion, just 
not gui.messageBox because too much NVDA internal nonsense is wrapped around it.

**Comment by nvdaes** [comment]
Fixed in #15

**Comment by XLTechie** [comment]
Thanks! I have not looked yet, but I'm sure it is good.
